#!/usr/bin/env bash
# When querying Nginx at its root / with a GET request it must return a page that contains the string Hello World!.
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
