#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get install haproxy
sudo service haproxy start
sudo sed -i "s|ENABLED=0|ENABLED=1|" /etc/default/haproxy
sudo service haproxy restart

sudo echo -e "\nfrontend myfrontend\n\tmode http\n\tbind *:80\n\tstats enable\n\tdefault_backend web_servers" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\nbackend web_servers\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 291743-web-01 34.204.91.178\n\tserver 291743-web-02 54.86.227.214" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
