#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2.
# facebook.com resolves to 8.8.8.8.
sudo cp /etc/hosts ~/hosts.bak
sed -i 's/127.0.0.1/127.0.0.2/;2i8.8.8.8 facebook.com' ~/hosts.bak
sudo cp ~/hosts.bak /etc/hosts
